name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    strategy:
      matrix:
        node: ['12', '14', '16']
    runs-on: ubuntu-latest
    env:
      SANDBOX_SKIP_DOWNLOAD: true
    name: Node ${{ matrix.node }} test
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: |
          npm install
          npm run build
          npm test
